version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      docker: 18
  pre_build:
    commands:
      - $(aws ecr get-login --region us-west-2 --no-include-email)
      - API_REPOSITORY=070576520712.dkr.ecr.us-west-2.amazonaws.com/confirmation-api
      - SERVICE_REPOSITORY=070576520712.dkr.ecr.us-west-2.amazonaws.com/confirmation-service
      - CLOUDFRONT_DISTRIBUTION_ID=ELC5E2SMZK2I
      - S3_BUCKET=southwest.andrewjdonley.com
  build:
    commands:
      - echo Build started on `date`
      - cd api
      - docker build -t $API_REPOSITORY .
      - cd ../confirmation_service
      - docker build -t $SERVICE_REPOSITORY .
      - cd ../frontend
      - npm run build
      - cd ..
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $API_REPOSITORY
      - docker push $SERVICE_REPOSITORY
      - aws s3 rm s3://$S3_BUCKET --recursive
      - aws s3 cp dist/frontend s3://$S3_BUCKET --recursive
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
      - echo Writing image definitions file...
      - printf '[{"name":"checkin-api","imageUri":"%s"}, {"name":"checkin-service","imageUri":"%s"}]' $REPOSITORY_URI:latest $SERVICE_REPOSITORY:latest  > imagedefinitions.json
artifacts:
    files: imagedefinitions.json