version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      docker: 18
  pre_build:
    commands:
      - $(aws ecr get-login --region us-west-2 --no-include-email)
      - API_REPOSITORY=070576520712.dkr.ecr.us-west-2.amazonaws.com/confirmation-api
      - SERVICE_REPOSITORY=070576520712.dkr.ecr.us-west-2.amazonaws.com/confirmation-service
  build:
    commands:
      - echo Build started on `date`
      - cd api
      - docker build -t $API_REPOSITORY .
      - cd ../confirmation_service
      - docker build -t $SERVICE_REPOSITORY .
      - cd ..
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI
      - docker push $SERVICE_REPOSITORY
      - echo Writing image definitions file...
      - printf '[{"name":"checkin-api","imageUri":"%s"}, {"name":"checkin-service","imageUri":"%s"}]' $REPOSITORY_URI:latest $SERVICE_REPOSITORY:latest  > imagedefinitions.json
artifacts:
    files: imagedefinitions.json