version: "3.7"

services:
  frontend:
    build: frontend/
    ports:
      - "4200:4200"
  api:
    build: api/
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:80"
    links:
      - redis
    volumes:
      - "./api:/app"
  confirmation-service:
    build: confirmation_service/
    environment:
      - REDIS_HOST=redis
    ports:
      - "5001:5001"
    links:
      - redis
    volumes:
      - "./confirmation_service:/app"
  redis:
    image: redis