version: "3.7"

services:
  frontend:
    build: frontend/
    ports:
      - "4200:4200"
  backend:
    build: .
    environment:
      - REDIS_HOST=redis
    ports:
      - "5000:80"
    volumes:
      - "./:/app"
  redis:
    image: redis